Работа над ошибками
dmitrykorchagin/ubereats-demo-frontend pull request #4
Opened 2018-05-24 22:23 UTC by dmitrykorchagin

Убрал директорию ubereats
Упростил код, убрал лишнию вложенность

2018-06-03 20:28 UTC, evgenyrodionov commented
Мерджконфликт можно было и самому исправить

2018-06-03 20:28 UTC, evgenyrodionov commented
Утром проверю

2018-06-05 17:53 UTC, imevro requested changes
очень огромная вложенность элементов, упрощай

2018-06-05 17:53 UTC, imevro commented on build/styles/normalize.css
> +/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
что это тут делает? всю директорию билда в игнор, гит для исходного кода, а не всего

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +        <div class="header-navigation__logo header-navigation__item">
а зачем тут ещё один див?

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +          <a class="header-navigation__logo--img" href="#"></a>
почему нет картинки? засунь в img

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +          <div class="header-location__item header-location__item--time">
убери этот итем-хуитем, он у тебя на каждом элементе, в чём смысл? максимум, где может быть итем — на элементе списка (li, он же list item)

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +          <div class="header-button">
ещё одна вложенность бессмысленная

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +          <button class="header-button__basket"></button>
опять же, картинка зачем-то сделана не через img

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +        <form action="#" class="search-restaurant">
почему бы не повесить этот header-search на форму?

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +                <span class="restaurant-info__price">&#8381;&#8381;</span>
у тебя юникод, нет нужды так изъебываться

2018-06-05 17:53 UTC, imevro commented on src/index.html
> +              <div class="restaurant-card__info restaurant-info">
зачем тут два класса?

2018-06-05 17:53 UTC, imevro commented on src/index2.html
> +  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.css">
нормалайз подключается ДО своих стилей

2018-06-05 17:53 UTC, imevro commented on src/index2.html
> +<!DOCTYPE html>
слабое название файла

2018-06-05 17:53 UTC, imevro commented on src/index2.html
> +                  <h3 class="dish-card__name">Язык говяжий с хреном</h3>
это всё можно вынести спокойно на уровень dish-card

2018-06-05 17:53 UTC, imevro commented on src/styles/normalize.css
> +/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
зачем это тут, если ты используешь сдн?

2018-06-11 00:09 UTC, dmitrykorchagin commented
@evgenyrodionov внес правки

2018-06-18 05:42 UTC, evgenyrodionov commented
гитхаб настрой, у тебя не цепляются коммиты к твоему аккаунту

2018-06-18 05:50 UTC, imevro requested changes

2018-06-18 05:50 UTC, evgenyrodionov commented on .gitignore
> +build
можно убрать предыдущую строчку

2018-06-18 05:50 UTC, evgenyrodionov commented on src/index.html
> +        <form class="header-navigation__element header-location--desktop">
лучше не стало

2018-06-18 05:50 UTC, evgenyrodionov commented on src/restaurant-list.html
> +              <p class="dish-card__name--detail"></p>
что это?

2018-06-18 05:50 UTC, evgenyrodionov commented on src/restaurant-list.html
> +            <article class="dish-card clearfix">
clearfix? в 2018?

2018-06-18 05:50 UTC, evgenyrodionov commented on src/styles/styles2.css
> +  float: right;
нет

2018-08-13 09:05 UTC, merged